### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by gabe7384** [LuckFire/toast-tester#1]
deletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedeletedelete

**Comment by LuckFire** [comment]
NO
FRICK OOFFF

**Comment by gabe7384** [comment]
![Screenshot (143)](https://user-images.githubusercontent.com/69572254/106238268-88ba4c80-61ce-11eb-86d8-730c6c840858.png)

**Comment by gabe7384** [comment]
:///

**Comment by LuckFire** [comment]
SHHH
